import React, { useState, useEffect } from 'react';
import { Plus, Trash2, Search, UploadCloud, AlertTriangle, Loader2, FileSpreadsheet } from 'lucide-react';
import { getStudents, syncStudentsBatch } from '../../services/storage';
import { Student } from '../../types';
import { GRADES, CLASSES } from '../../constants';

// Declare XLSX for TypeScript since it's loaded via CDN in index.html
declare var XLSX: any;

const Students: React.FC = () => {
  const [students, setStudents] = useState<Student[]>([]);
  const [loading, setLoading] = useState(true);
  const [showAddModal, setShowAddModal] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const [processingFile, setProcessingFile] = useState(false);
  
  // New Student Form State
  const [newName, setNewName] = useState('');
  const [newId, setNewId] = useState('');
  const [newGrade, setNewGrade] = useState(GRADES[0]);
  const [newClass, setNewClass] = useState(CLASSES[0]);
  const [newPhone, setNewPhone] = useState('');

  const fetchStudents = async () => {
    setLoading(true);
    try {
        const data = await getStudents();
        setStudents(data);
    } catch (e) {
        console.error("Error fetching students:", e);
    } finally {
        setLoading(false);
    }
  };

  useEffect(() => {
    fetchStudents();
  }, []);

  const handleAddStudent = async (e: React.FormEvent) => {
    e.preventDefault();
    if (students.some(s => s.studentId === newId)) {
        alert("رقم الهوية مسجل مسبقاً لطالب آخر.");
        return;
    }
    
    const newStudent: Student = {
      id: '', // Generated by logic
      name: newName,
      studentId: newId,
      grade: newGrade,
      className: newClass,
      phone: newPhone
    };

    await syncStudentsBatch([newStudent], [], []);
    await fetchStudents();
    setShowAddModal(false);
    setNewName(''); setNewId(''); setNewPhone('');
  };

  const handleDelete = async (id: string) => {
    if (window.confirm('هل أنت متأكد من حذف هذا الطالب؟')) {
      await syncStudentsBatch([], [], [id]);
      fetchStudents();
    }
  };

  const mapCodeToGrade = (code: string | number): string => {
    const c = code ? code.toString().trim() : '';
    if (c === '725' || c === '0725') return 'الأول متوسط';
    if (c === '825' || c === '0825') return 'الثاني متوسط';
    if (c === '925' || c === '0925') return 'الثالث متوسط';
    if (GRADES.includes(c)) return c;
    return ''; // Return empty if not matched, to be handled later
  };

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (typeof XLSX === 'undefined') {
        alert("مكتبة معالجة الملفات (SheetJS) غير محملة. يرجى تحديث الصفحة.");
        return;
    }

    setProcessingFile(true);
    
    try {
        const reader = new FileReader();
        reader.onload = async (evt) => {
            const bstr = evt.target?.result;
            const wb = XLSX.read(bstr, { type: 'binary' });
            const wsname = wb.SheetNames[0];
            const ws = wb.Sheets[wsname];
            // Read as array of arrays to handle headers manually if needed, or JSON
            const data = XLSX.utils.sheet_to_json(ws);
            
            // Process Data
            const toAdd: Student[] = [];
            const toUpdate: Student[] = [];
            const currentStudentsMap = new Map<string, Student>(students.map(s => [s.studentId, s]));

            data.forEach((row: any) => {
                // Expected Columns: "الاسم", "السجل المدني" (or similar), "الصف", "الفصل", "الجوال"
                // Let's try to be flexible with keys
                const name = row['الاسم'] || row['name'] || row['Name'];
                const studentIdRaw = row['السجل المدني'] || row['الهوية'] || row['studentId'] || row['ID'];
                const gradeRaw = row['الصف'] || row['grade'] || row['Grade'];
                const classRaw = row['الفصل'] || row['className'] || row['Class'];
                const phone = row['الجوال'] || row['رقم الجوال'] || row['phone'] || row['Phone'] || '';

                if (name && studentIdRaw) {
                    const studentId = studentIdRaw.toString().trim();
                    const grade = mapCodeToGrade(gradeRaw) || GRADES[0]; // Fallback if mapping fails
                    const className = classRaw ? classRaw.toString().trim() : CLASSES[0];

                    const studentObj: Student = {
                        id: '', // Placeholder
                        name: name.toString().trim(),
                        studentId: studentId,
                        grade: grade,
                        className: className,
                        phone: phone.toString().trim()
                    };

                    if (currentStudentsMap.has(studentId)) {
                        // Update existing
                        const existing = currentStudentsMap.get(studentId)!;
                        toUpdate.push({ ...studentObj, id: existing.id });
                    } else {
                        // Add new
                        toAdd.push(studentObj);
                    }
                }
            });

            if (toAdd.length === 0 && toUpdate.length === 0) {
                alert("لم يتم العثور على بيانات صالحة في الملف. تأكد من أسماء الأعمدة (الاسم، السجل المدني، الصف، الفصل).");
                setProcessingFile(false);
                return;
            }

            const confirmMsg = `تم تحليل الملف:\n➕ إضافة طلاب جدد: ${toAdd.length}\n🔄 تحديث بيانات: ${toUpdate.length}\n\nهل تريد تنفيذ العملية؟`;
            if (window.confirm(confirmMsg)) {
                await syncStudentsBatch(toAdd, toUpdate, []); // Pass empty array for delete
                await fetchStudents();
                alert("تم رفع البيانات بنجاح!");
            }
            setProcessingFile(false);
            e.target.value = ''; // Reset input
        };
        reader.readAsBinaryString(file);
    } catch (error) {
        console.error(error);
        alert("حدث خطأ أثناء قراءة الملف.");
        setProcessingFile(false);
    }
  };

  const filteredStudents = students.filter(s => 
    s.name.includes(searchTerm) || s.studentId.includes(searchTerm)
  );

  const inputClasses = "w-full p-2.5 bg-white border border-slate-300 text-slate-900 rounded-lg focus:ring-2 focus:ring-blue-900 focus:border-blue-900 outline-none transition-all";
  const labelClasses = "block text-sm font-semibold text-slate-700 mb-1.5";

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row justify-between items-center gap-4">
        <div>
            <h1 className="text-2xl font-bold text-blue-900">إدارة الطلاب</h1>
            <p className="text-slate-500 text-sm mt-1">رفع وإدارة بيانات الطلاب</p>
        </div>
        <div className="flex gap-2">
           <button 
            onClick={() => setShowAddModal(true)}
            className="flex items-center gap-2 bg-blue-900 text-white px-4 py-2 rounded-lg hover:bg-blue-800 transition-colors font-medium shadow-sm hover:shadow"
           >
             <Plus size={18} /> إضافة يدوي
           </button>
           
           <div className="relative">
             <input 
                type="file" 
                accept=".xlsx, .xls"
                onChange={handleFileUpload}
                className="hidden"
                id="excel-upload"
                disabled={processingFile}
             />
             <label 
                htmlFor="excel-upload"
                className={`flex items-center gap-2 bg-emerald-600 text-white px-4 py-2 rounded-lg hover:bg-emerald-700 transition-colors font-medium shadow-sm hover:shadow cursor-pointer ${processingFile ? 'opacity-50 cursor-wait' : ''}`}
             >
                {processingFile ? <Loader2 className="animate-spin" size={18} /> : <FileSpreadsheet size={18} />}
                <span>{processingFile ? 'جاري المعالجة...' : 'رفع ملف Excel'}</span>
             </label>
           </div>
        </div>
      </div>

      <div className="bg-white p-4 rounded-xl shadow-sm border border-slate-200">
        <div className="relative max-w-md w-full">
          <Search className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400" size={20} />
          <input 
            type="text" 
            placeholder="بحث بالاسم أو رقم الهوية..." 
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full pr-10 pl-4 py-2.5 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-900 outline-none text-slate-900"
          />
        </div>
      </div>

      <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
        {loading ? (
            <div className="p-12 text-center text-slate-500">
                <Loader2 className="animate-spin mx-auto mb-2" size={32} />
                <p>جاري تحميل بيانات الطلاب من السحابة...</p>
            </div>
        ) : (
        <div className="overflow-x-auto">
            <table className="w-full text-right min-w-[600px]">
            <thead className="bg-slate-50 text-slate-700 text-sm font-bold border-b border-slate-200">
                <tr>
                <th className="p-4">الاسم</th>
                <th className="p-4">الهوية</th>
                <th className="p-4">الصف</th>
                <th className="p-4">الفصل</th>
                <th className="p-4">الجوال</th>
                <th className="p-4">إجراء</th>
                </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
                {filteredStudents.map(s => (
                <tr key={s.id} className="hover:bg-slate-50 transition-colors">
                    <td className="p-4 font-bold text-slate-900">{s.name}</td>
                    <td className="p-4 font-mono text-slate-600">{s.studentId}</td>
                    <td className="p-4 text-slate-700">{s.grade}</td>
                    <td className="p-4 text-slate-700">{s.className}</td>
                    <td className="p-4 text-slate-700 dir-ltr text-right">{s.phone}</td>
                    <td className="p-4">
                    <button onClick={() => handleDelete(s.id)} className="text-red-400 hover:text-red-600 p-2 hover:bg-red-50 rounded-lg transition-colors"><Trash2 size={18}/></button>
                    </td>
                </tr>
                ))}
                {filteredStudents.length === 0 && (
                    <tr>
                        <td colSpan={6} className="p-12 text-center text-slate-500">
                            <AlertTriangle size={48} className="mx-auto mb-2 opacity-50" />
                            <p>لا توجد بيانات طلاب. قم بإضافة طلاب أو رفع ملف Excel.</p>
                        </td>
                    </tr>
                )}
            </tbody>
            </table>
        </div>
        )}
      </div>

      {/* Add Modal */}
      {showAddModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
           <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md p-6 animate-fade-in-up border border-slate-100">
              <div className="flex justify-between items-center mb-6 border-b border-slate-100 pb-4">
                 <h2 className="text-xl font-bold text-slate-800">إضافة طالب جديد</h2>
                 <button onClick={() => setShowAddModal(false)} className="text-slate-400 hover:text-slate-600">✕</button>
              </div>
              
              <form onSubmit={handleAddStudent} className="space-y-4">
                 <div>
                   <label className={labelClasses}>الاسم الثلاثي</label>
                   <input required value={newName} onChange={e => setNewName(e.target.value)} className={inputClasses} placeholder="مثال: أحمد محمد علي" />
                 </div>
                 <div>
                   <label className={labelClasses}>رقم الهوية / السجل</label>
                   <input required value={newId} onChange={e => setNewId(e.target.value)} className={inputClasses} placeholder="1xxxxxxxxx" />
                 </div>
                 <div className="grid grid-cols-2 gap-4">
                    <div>
                       <label className={labelClasses}>الصف</label>
                       <select value={newGrade} onChange={e => setNewGrade(e.target.value)} className={inputClasses}>
                          {GRADES.map(g => <option key={g} value={g}>{g}</option>)}
                       </select>
                    </div>
                    <div>
                       <label className={labelClasses}>الفصل</label>
                       <select value={newClass} onChange={e => setNewClass(e.target.value)} className={inputClasses}>
                          {CLASSES.map(c => <option key={c} value={c}>{c}</option>)}
                       </select>
                    </div>
                 </div>
                 <div>
                   <label className={labelClasses}>رقم الجوال</label>
                   <input required value={newPhone} onChange={e => setNewPhone(e.target.value)} className={inputClasses} placeholder="05xxxxxxxx" />
                 </div>
                 <div className="flex gap-3 pt-4">
                   <button type="submit" className="flex-1 bg-blue-900 text-white py-2.5 rounded-lg hover:bg-blue-800 font-bold transition-colors shadow-lg shadow-blue-900/20">حفظ البيانات</button>
                   <button type="button" onClick={() => setShowAddModal(false)} className="flex-1 bg-slate-100 text-slate-700 py-2.5 rounded-lg hover:bg-slate-200 font-bold transition-colors">إلغاء</button>
                 </div>
              </form>
           </div>
        </div>
      )}
    </div>
  );
};

export default Students;