
import React, { useState, useEffect, useMemo } from 'react';
import { Plus, Trash2, Search, UploadCloud, AlertTriangle, Loader2, FileSpreadsheet, RefreshCw, CheckSquare, Square, X, AlertCircle, WifiOff } from 'lucide-react';
import { getStudents, syncStudentsBatch, getStudentsSync, addStudent, deleteStudent } from '../../services/storage';
import { Student } from '../../types';
import { GRADES, CLASSES } from '../../constants';

// Declare XLSX for TypeScript since it's loaded via CDN in index.html
declare var XLSX: any;

const Students: React.FC = () => {
  // Instant Load: Initialize with cached data if available
  const [students, setStudents] = useState<Student[]>(() => getStudentsSync() || []);
  
  // Only show loading if we don't have data
  const [loading, setLoading] = useState(() => !getStudentsSync());
  const [error, setError] = useState<string | null>(null);
  
  const [showAddModal, setShowAddModal] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const [processingFile, setProcessingFile] = useState(false);
  const [selectedIds, setSelectedIds] = useState<string[]>([]);
  const [isBulkDeleting, setIsBulkDeleting] = useState(false);
  
  // New Student Form State
  const [newName, setNewName] = useState('');
  const [newId, setNewId] = useState('');
  const [newGrade, setNewGrade] = useState(GRADES[0]);
  const [newClass, setNewClass] = useState(CLASSES[0]);
  const [newPhone, setNewPhone] = useState('');

  const fetchStudents = async (force = false) => {
    // If we are forcing refresh or have no initial data, show loading state
    if (force || students.length === 0) {
      setLoading(true);
    }
    setError(null);
    
    try {
        console.log("Fetching students...");
        const data = await getStudents(force);
        setStudents(data);
    } catch (e: any) {
        console.error("Error fetching students in component:", e);
        setError(e.message || "تعذر جلب البيانات. يرجى التحقق من الاتصال بالإنترنت.");
    } finally {
        // Ensure loading is turned off regardless of success/failure
        setLoading(false);
    }
  };

  useEffect(() => {
    // Initial fetch
    fetchStudents();
  }, []);

  const handleRefresh = () => {
    fetchStudents(true);
  };

  const filteredStudents = useMemo(() => {
    return students.filter(s => 
      s.name.includes(searchTerm) || s.studentId.includes(searchTerm)
    );
  }, [students, searchTerm]);

  // --- Bulk Selection Logic ---

  const handleSelectAll = () => {
    if (selectedIds.length === filteredStudents.length) {
      setSelectedIds([]);
    } else {
      setSelectedIds(filteredStudents.map(s => s.id));
    }
  };

  const handleSelectOne = (id: string) => {
    if (selectedIds.includes(id)) {
      setSelectedIds(prev => prev.filter(item => item !== id));
    } else {
      setSelectedIds(prev => [...prev, id]);
    }
  };

  const handleBulkDelete = async () => {
    if (!window.confirm(`هل أنت متأكد من حذف ${selectedIds.length} طالب؟ لا يمكن التراجع عن هذا الإجراء.`)) {
      return;
    }

    setIsBulkDeleting(true);
    const previousStudents = [...students];
    
    // Optimistic Update
    setStudents(prev => prev.filter(s => !selectedIds.includes(s.id)));

    try {
      // Pass empty add/update arrays, only IDs to delete
      await syncStudentsBatch([], [], selectedIds);
      setSelectedIds([]);
    } catch (error) {
      alert("حدث خطأ أثناء الحذف الجماعي.");
      setStudents(previousStudents); // Revert
    } finally {
      setIsBulkDeleting(false);
    }
  };

  // --- Single Add/Delete Logic ---

  const handleAddStudent = async (e: React.FormEvent) => {
    e.preventDefault();
    if (students.some(s => s.studentId === newId)) {
        alert("رقم الهوية مسجل مسبقاً لطالب آخر.");
        return;
    }
    
    const newStudent: Student = {
      id: '', // Generated by DB
      name: newName,
      studentId: newId,
      grade: newGrade,
      className: newClass,
      phone: newPhone
    };

    setLoading(true); 
    try {
      const addedStudent = await addStudent(newStudent);
      setStudents(prev => [...prev, addedStudent]);
      setShowAddModal(false);
      setNewName(''); setNewId(''); setNewPhone('');
    } catch (error) {
      alert("حدث خطأ أثناء الإضافة.");
    } finally {
      setLoading(false);
    }
  };

  const handleDelete = async (id: string) => {
    if (window.confirm('هل أنت متأكد من حذف هذا الطالب؟')) {
      const previousStudents = [...students];
      setStudents(prev => prev.filter(s => s.id !== id));
      try {
        await deleteStudent(id);
      } catch (error) {
        alert("فشل الحذف.");
        setStudents(previousStudents);
      }
    }
  };

  // --- File Upload Logic ---

  const mapCodeToGrade = (code: string | number): string => {
    const c = code ? code.toString().trim() : '';
    if (c === '725' || c === '0725') return 'الأول متوسط';
    if (c === '825' || c === '0825') return 'الثاني متوسط';
    if (c === '925' || c === '0925') return 'الثالث متوسط';
    if (GRADES.includes(c)) return c;
    return ''; 
  };

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (typeof XLSX === 'undefined') {
        alert("مكتبة معالجة الملفات (SheetJS) غير محملة. يرجى تحديث الصفحة.");
        return;
    }

    setProcessingFile(true);
    
    try {
        const arrayBuffer = await new Promise<ArrayBuffer>((resolve, reject) => {
             const reader = new FileReader();
             reader.onload = (evt) => {
                 if (evt.target?.result) resolve(evt.target.result as ArrayBuffer);
                 else reject(new Error("Empty file"));
             };
             reader.onerror = (err) => reject(err);
             reader.readAsArrayBuffer(file);
        });

        const wb = XLSX.read(arrayBuffer, { type: 'array' });
        const wsname = wb.SheetNames[0];
        const ws = wb.Sheets[wsname];
        const data = XLSX.utils.sheet_to_json(ws);
        
        if (data.length === 0) {
            alert("الملف فارغ!");
            return;
        }

        // Validate Headers
        const firstRow = data[0] as object;
        const keys = Object.keys(firstRow);
        const hasName = keys.some(k => ['الاسم', 'name', 'Name'].includes(k));
        const hasId = keys.some(k => ['السجل المدني', 'الهوية', 'studentId', 'ID'].includes(k));
        
        if (!hasName || !hasId) {
            alert("صيغة الملف غير صحيحة. يجب أن يحتوي الملف على الأعمدة التالية: 'الاسم'، 'السجل المدني' (أو الهوية).");
            return;
        }

        const toUpsert: Student[] = [];
        const errors: string[] = [];

        data.forEach((row: any, index: number) => {
            const name = row['الاسم'] || row['name'] || row['Name'];
            const studentIdRaw = row['السجل المدني'] || row['الهوية'] || row['studentId'] || row['ID'];
            const gradeRaw = row['الصف'] || row['grade'] || row['Grade'];
            const classRaw = row['الفصل'] || row['className'] || row['Class'];
            const phone = row['الجوال'] || row['رقم الجوال'] || row['phone'] || row['Phone'] || '';

            if (name && studentIdRaw) {
                const studentId = studentIdRaw.toString().trim();
                const grade = mapCodeToGrade(gradeRaw) || GRADES[0]; 
                const className = classRaw ? classRaw.toString().trim() : CLASSES[0];

                const studentObj: Student = {
                    id: '', // Not needed for Upsert if using student_id as key
                    name: name.toString().trim(),
                    studentId: studentId,
                    grade: grade,
                    className: className,
                    phone: phone.toString().trim()
                };
                toUpsert.push(studentObj);
            } else {
                if (!name && !studentIdRaw) return; 
                errors.push(`صف رقم ${index + 2}: بيانات ناقصة (الاسم أو الهوية)`);
            }
        });

        if (toUpsert.length === 0) {
            alert("لم يتم العثور على أي طلاب صالحين للإضافة.");
            return;
        }

        const confirmMsg = `سيتم معالجة ${toUpsert.length} طالب.\nسيتم إضافة الطلاب الجدد وتحديث بيانات الطلاب الموجودين مسبقاً.\n\nهل تريد المتابعة؟`;
        
        if (window.confirm(confirmMsg)) {
            // Pass toAdd as the whole list (syncStudentsBatch will handle Upsert)
            await syncStudentsBatch(toUpsert, [], []); 
            await fetchStudents(true); 
            alert("تمت العملية بنجاح!");
        }

    } catch (error: any) {
        console.error(error);
        alert(`حدث خطأ: ${error.message}`);
    } finally {
        setProcessingFile(false);
        e.target.value = ''; // Reset input
    }
  };

  const inputClasses = "w-full p-2.5 bg-white border border-slate-300 text-slate-900 rounded-lg focus:ring-2 focus:ring-blue-900 focus:border-blue-900 outline-none transition-all";
  const labelClasses = "block text-sm font-semibold text-slate-700 mb-1.5";

  return (
    <div className="space-y-6 animate-fade-in relative">
      <div className="flex flex-col md:flex-row justify-between items-center gap-4">
        <div>
            <h1 className="text-2xl font-bold text-blue-900">إدارة الطلاب</h1>
            <p className="text-slate-500 text-sm mt-1">رفع وإدارة بيانات الطلاب (Supabase Cloud)</p>
        </div>
        <div className="flex gap-2">
           <button 
             onClick={handleRefresh}
             className="flex items-center gap-2 bg-slate-100 text-slate-600 px-3 py-2 rounded-lg hover:bg-slate-200 transition-colors font-medium"
             title="تحديث البيانات من السيرفر"
           >
             <RefreshCw size={18} className={loading ? 'animate-spin' : ''} />
           </button>
           <button 
            onClick={() => setShowAddModal(true)}
            className="flex items-center gap-2 bg-blue-900 text-white px-4 py-2 rounded-lg hover:bg-blue-800 transition-colors font-medium shadow-sm hover:shadow"
           >
             <Plus size={18} /> إضافة يدوي
           </button>
           
           <div className="relative">
             <input 
                type="file" 
                accept=".xlsx, .xls"
                onChange={handleFileUpload}
                className="hidden"
                id="excel-upload"
                disabled={processingFile}
             />
             <label 
                htmlFor="excel-upload"
                className={`flex items-center gap-2 bg-emerald-600 text-white px-4 py-2 rounded-lg hover:bg-emerald-700 transition-colors font-medium shadow-sm hover:shadow cursor-pointer ${processingFile ? 'opacity-50 cursor-wait' : ''}`}
             >
                {processingFile ? <Loader2 className="animate-spin" size={18} /> : <FileSpreadsheet size={18} />}
                <span>{processingFile ? 'جاري المعالجة...' : 'رفع ملف Excel'}</span>
             </label>
           </div>
        </div>
      </div>

      <div className="bg-white p-4 rounded-xl shadow-sm border border-slate-200">
        <div className="relative max-w-md w-full">
          <Search className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400" size={20} />
          <input 
            type="text" 
            placeholder="بحث بالاسم أو رقم الهوية..." 
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full pr-10 pl-4 py-2.5 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-900 outline-none text-slate-900"
          />
        </div>
      </div>

      {/* Bulk Action Bar */}
      {selectedIds.length > 0 && (
        <div className="bg-red-50 border border-red-100 p-4 rounded-xl flex justify-between items-center animate-fade-in shadow-sm">
           <div className="flex items-center gap-3 text-red-800 font-bold">
              <CheckSquare size={20} />
              <span>تم تحديد {selectedIds.length} طالب</span>
           </div>
           <div className="flex gap-3">
              <button 
                onClick={() => setSelectedIds([])}
                className="px-4 py-2 rounded-lg bg-white border border-red-100 text-red-600 hover:bg-red-100 text-sm font-bold"
              >
                إلغاء التحديد
              </button>
              <button 
                onClick={handleBulkDelete}
                disabled={isBulkDeleting}
                className="px-4 py-2 rounded-lg bg-red-600 text-white hover:bg-red-700 text-sm font-bold shadow-sm flex items-center gap-2"
              >
                {isBulkDeleting ? <Loader2 className="animate-spin" size={16}/> : <Trash2 size={16} />}
                حذف المحدد
              </button>
           </div>
        </div>
      )}

      {/* Error Banner */}
      {error && (
        <div className="bg-red-50 border border-red-200 p-4 rounded-xl flex items-center gap-3 text-red-800 mb-4">
            <WifiOff size={24} />
            <div>
                <p className="font-bold">فشل الاتصال!</p>
                <p className="text-sm">{error}</p>
                <button onClick={handleRefresh} className="mt-2 text-sm underline font-bold hover:text-red-950">حاول مرة أخرى</button>
            </div>
        </div>
      )}

      {/* Table Container */}
      <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden h-[600px] flex flex-col">
        {/* Table Header - Static Flex Div */}
        <div className="flex bg-slate-50 text-slate-700 text-sm font-bold border-b border-slate-200 pr-2 pl-4 py-4 uppercase tracking-wider">
            <div className="w-[5%] text-center">
                <button onClick={handleSelectAll} className="text-slate-500 hover:text-blue-900 transition-colors">
                    {selectedIds.length > 0 && selectedIds.length === filteredStudents.length 
                    ? <CheckSquare size={18} /> 
                    : <Square size={18} />}
                </button>
            </div>
            <div className="w-[25%] px-2">الاسم</div>
            <div className="w-[15%] px-2">الهوية</div>
            <div className="w-[15%] px-2">الصف</div>
            <div className="w-[10%] px-2">الفصل</div>
            <div className="w-[20%] px-2">الجوال</div>
            <div className="w-[10%] text-center">إجراء</div>
        </div>

        {loading ? (
            <div className="flex-1 flex flex-col items-center justify-center text-slate-500">
                <Loader2 className="animate-spin mx-auto mb-2" size={32} />
                <p>جاري تحميل بيانات الطلاب...</p>
            </div>
        ) : filteredStudents.length === 0 && !error ? (
            <div className="flex-1 flex flex-col items-center justify-center text-slate-500 p-12">
                <AlertTriangle size={48} className="mx-auto mb-2 opacity-50" />
                <p>لا توجد بيانات طلاب. قم بإضافة طلاب أو رفع ملف Excel.</p>
            </div>
        ) : !error ? (
            // Standard List (No react-window)
            <div className="flex-1 overflow-y-auto scrollbar-thin scrollbar-thumb-slate-200 scrollbar-track-transparent">
                 {filteredStudents.map((s) => {
                    const isSelected = selectedIds.includes(s.id);
                    return (
                      <div 
                        key={s.id}
                        className={`flex items-center border-b border-slate-50 hover:bg-slate-50 transition-colors px-2 text-sm h-[60px] ${isSelected ? 'bg-blue-50/50' : ''}`}
                      >
                        {/* Checkbox (5%) */}
                        <div className="w-[5%] flex justify-center">
                            <button 
                                onClick={() => handleSelectOne(s.id)} 
                                className={`${isSelected ? 'text-blue-900' : 'text-slate-300 hover:text-slate-400'}`}
                            >
                                {isSelected ? <CheckSquare size={18} /> : <Square size={18} />}
                            </button>
                        </div>

                        {/* Name (25%) */}
                        <div className="w-[25%] p-2 font-bold text-slate-900 truncate">
                            {s.name}
                        </div>

                        {/* ID (15%) */}
                        <div className="w-[15%] p-2 font-mono text-slate-600 truncate">
                            {s.studentId}
                        </div>

                        {/* Grade (15%) */}
                        <div className="w-[15%] p-2 text-slate-700 truncate">
                            {s.grade}
                        </div>

                        {/* Class (10%) */}
                        <div className="w-[10%] p-2 text-slate-700 truncate">
                            {s.className}
                        </div>

                        {/* Phone (20%) */}
                        <div className="w-[20%] p-2 text-slate-700 dir-ltr text-right truncate">
                            {s.phone}
                        </div>

                        {/* Action (10%) */}
                        <div className="w-[10%] p-2 flex justify-center">
                            <button onClick={() => handleDelete(s.id)} className="text-red-400 hover:text-red-600 p-1.5 hover:bg-red-50 rounded-lg transition-colors">
                                <Trash2 size={16}/>
                            </button>
                        </div>
                      </div>
                    );
                 })}
            </div>
        ) : (
            <div className="flex-1 bg-slate-50"></div>
        )}
      </div>

      {/* Add Modal */}
      {showAddModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
           <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md p-6 animate-fade-in-up border border-slate-100">
              <div className="flex justify-between items-center mb-6 border-b border-slate-100 pb-4">
                 <h2 className="text-xl font-bold text-slate-800">إضافة طالب جديد</h2>
                 <button onClick={() => setShowAddModal(false)} className="text-slate-400 hover:text-slate-600">✕</button>
              </div>
              
              <form onSubmit={handleAddStudent} className="space-y-4">
                 <div>
                   <label className={labelClasses}>الاسم الثلاثي</label>
                   <input required value={newName} onChange={e => setNewName(e.target.value)} className={inputClasses} placeholder="مثال: أحمد محمد علي" />
                 </div>
                 <div>
                   <label className={labelClasses}>رقم الهوية / السجل</label>
                   <input required value={newId} onChange={e => setNewId(e.target.value)} className={inputClasses} placeholder="1xxxxxxxxx" />
                 </div>
                 <div className="grid grid-cols-2 gap-4">
                    <div>
                       <label className={labelClasses}>الصف</label>
                       <select value={newGrade} onChange={e => setNewGrade(e.target.value)} className={inputClasses}>
                          {GRADES.map(g => <option key={g} value={g}>{g}</option>)}
                       </select>
                    </div>
                    <div>
                       <label className={labelClasses}>الفصل</label>
                       <select value={newClass} onChange={e => setNewClass(e.target.value)} className={inputClasses}>
                          {CLASSES.map(c => <option key={c} value={c}>{c}</option>)}
                       </select>
                    </div>
                 </div>
                 <div>
                   <label className={labelClasses}>رقم الجوال</label>
                   <input required value={newPhone} onChange={e => setNewPhone(e.target.value)} className={inputClasses} placeholder="05xxxxxxxx" />
                 </div>
                 <div className="flex gap-3 pt-4">
                   <button type="submit" className="flex-1 bg-blue-900 text-white py-2.5 rounded-lg hover:bg-blue-800 font-bold transition-colors shadow-lg shadow-blue-900/20">حفظ البيانات</button>
                   <button type="button" onClick={() => setShowAddModal(false)} className="flex-1 bg-slate-100 text-slate-700 py-2.5 rounded-lg hover:bg-slate-200 font-bold transition-colors">إلغاء</button>
                 </div>
              </form>
           </div>
        </div>
      )}
    </div>
  );
};

export default Students;
