import React, { useState, useEffect } from 'react';
import { Plus, Trash2, Search, RefreshCw, AlertTriangle, Loader2 } from 'lucide-react';
import { getStudents, syncStudentsBatch, clearStudents } from '../../services/storage';
import { Student } from '../../types';
import { GRADES, CLASSES } from '../../constants';

const Students: React.FC = () => {
  const [students, setStudents] = useState<Student[]>([]);
  const [loading, setLoading] = useState(true);
  const [showAddModal, setShowAddModal] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  
  // New Student Form State
  const [newName, setNewName] = useState('');
  const [newId, setNewId] = useState('');
  const [newGrade, setNewGrade] = useState(GRADES[0]);
  const [newClass, setNewClass] = useState(CLASSES[0]);
  const [newPhone, setNewPhone] = useState('');

  const fetchStudents = async () => {
    setLoading(true);
    const data = await getStudents();
    setStudents(data);
    setLoading(false);
  };

  useEffect(() => {
    fetchStudents();
  }, []);

  const handleAddStudent = async (e: React.FormEvent) => {
    e.preventDefault();
    if (students.some(s => s.studentId === newId)) {
        alert("رقم الهوية مسجل مسبقاً لطالب آخر.");
        return;
    }
    
    // We treat single add as a small batch sync: 1 add, 0 update, 0 delete
    const newStudent: Student = {
      id: '', // Generated by firestore in logic
      name: newName,
      studentId: newId,
      grade: newGrade,
      className: newClass,
      phone: newPhone
    };

    await syncStudentsBatch([newStudent], [], []);
    await fetchStudents();
    setShowAddModal(false);
    setNewName(''); setNewId(''); setNewPhone('');
  };

  const handleDelete = async (id: string) => {
    if (window.confirm('هل أنت متأكد من حذف هذا الطالب؟')) {
      await syncStudentsBatch([], [], [id]);
      fetchStudents();
    }
  };

  const mapCodeToGrade = (code: string | number): string => {
    const c = code.toString();
    if (c === '725' || c === '0725') return 'الأول متوسط';
    if (c === '825' || c === '0825') return 'الثاني متوسط';
    if (c === '925' || c === '0925') return 'الثالث متوسط';
    if (GRADES.includes(c)) return c;
    return 'غير محدد';
  };

  const handleExcelSync = async () => {
    const confirmSync = window.confirm(
        "هل تريد بدء المزامنة؟ (تنبيه: هذا مجرد محاكاة، يرجى برمجة قارئ ملفات Excel فعلي لربطه)"
    );
    if (!confirmSync) return;

    setLoading(true);

    // Simulation Data
    const simulatedExcelData: Partial<Student>[] = [
      { studentId: "111222333", name: "أحمد محمد علي", grade: mapCodeToGrade("725"), className: "أ", phone: "0500000001" }, 
      { studentId: "444555666", name: "سارة خالد العمري", grade: mapCodeToGrade("725"), className: "أ", phone: "0500000002" },
      { studentId: "999111222", name: "خالد الفهد (جديد)", grade: mapCodeToGrade("725"), className: "ب", phone: "0555555555" },
    ];

    const currentStudents = students;
    const toAdd: Student[] = [];
    const toUpdate: Student[] = [];
    const toDeleteIds: string[] = [];

    // Identify Add/Update
    simulatedExcelData.forEach(excelStudent => {
        const existing = currentStudents.find(s => s.studentId === excelStudent.studentId);
        if (existing) {
            toUpdate.push({ ...existing, ...excelStudent } as Student);
        } else {
            toAdd.push({ ...excelStudent, id: '' } as Student);
        }
    });

    // Identify Delete (In DB but not in Excel)
    const excelIds = new Set(simulatedExcelData.map(s => s.studentId));
    currentStudents.forEach(s => {
        if (!excelIds.has(s.studentId)) {
            toDeleteIds.push(s.id);
        }
    });

    await syncStudentsBatch(toAdd, toUpdate, toDeleteIds);
    await fetchStudents();
    
    alert(`تمت المزامنة!\n➕ إضافة: ${toAdd.length}\n🔄 تحديث: ${toUpdate.length}\n🗑️ حذف: ${toDeleteIds.length}`);
  };

  const filteredStudents = students.filter(s => 
    s.name.includes(searchTerm) || s.studentId.includes(searchTerm)
  );

  const inputClasses = "w-full p-2.5 bg-white border border-slate-300 text-slate-900 rounded-lg focus:ring-2 focus:ring-blue-900 focus:border-blue-900 outline-none transition-all";
  const labelClasses = "block text-sm font-semibold text-slate-700 mb-1.5";

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row justify-between items-center gap-4">
        <div>
            <h1 className="text-2xl font-bold text-blue-900">إدارة الطلاب (سحابي)</h1>
            <p className="text-slate-500 text-sm mt-1">قاعدة بيانات الطلاب والمزامنة عبر Firebase</p>
        </div>
        <div className="flex gap-2">
           <button 
            onClick={() => setShowAddModal(true)}
            className="flex items-center gap-2 bg-blue-900 text-white px-4 py-2 rounded-lg hover:bg-blue-800 transition-colors font-medium shadow-sm hover:shadow"
           >
             <Plus size={18} /> إضافة يدوي
           </button>
           <button 
            onClick={handleExcelSync}
            className="flex items-center gap-2 bg-emerald-600 text-white px-4 py-2 rounded-lg hover:bg-emerald-700 transition-colors font-medium shadow-sm hover:shadow"
           >
             <RefreshCw size={18} /> مزامنة Excel
           </button>
        </div>
      </div>

      <div className="bg-white p-4 rounded-xl shadow-sm border border-slate-200">
        <div className="relative max-w-md w-full">
          <Search className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400" size={20} />
          <input 
            type="text" 
            placeholder="بحث بالاسم أو رقم الهوية..." 
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full pr-10 pl-4 py-2.5 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-900 outline-none text-slate-900"
          />
        </div>
      </div>

      <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
        {loading ? (
            <div className="p-12 text-center text-slate-500">
                <Loader2 className="animate-spin mx-auto mb-2" size={32} />
                <p>جاري تحميل بيانات الطلاب من السحابة...</p>
            </div>
        ) : (
        <div className="overflow-x-auto">
            <table className="w-full text-right min-w-[600px]">
            <thead className="bg-slate-50 text-slate-700 text-sm font-bold border-b border-slate-200">
                <tr>
                <th className="p-4">الاسم</th>
                <th className="p-4">الهوية</th>
                <th className="p-4">الصف</th>
                <th className="p-4">الفصل</th>
                <th className="p-4">الجوال</th>
                <th className="p-4">إجراء</th>
                </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
                {filteredStudents.map(s => (
                <tr key={s.id} className="hover:bg-slate-50 transition-colors">
                    <td className="p-4 font-bold text-slate-900">{s.name}</td>
                    <td className="p-4 font-mono text-slate-600">{s.studentId}</td>
                    <td className="p-4 text-slate-700">{s.grade}</td>
                    <td className="p-4 text-slate-700">{s.className}</td>
                    <td className="p-4 text-slate-700 dir-ltr text-right">{s.phone}</td>
                    <td className="p-4">
                    <button onClick={() => handleDelete(s.id)} className="text-red-400 hover:text-red-600 p-2 hover:bg-red-50 rounded-lg transition-colors"><Trash2 size={18}/></button>
                    </td>
                </tr>
                ))}
                {filteredStudents.length === 0 && (
                    <tr>
                        <td colSpan={6} className="p-12 text-center text-slate-500">
                            <AlertTriangle size={48} className="mx-auto mb-2 opacity-50" />
                            <p>لا توجد نتائج مطابقة</p>
                        </td>
                    </tr>
                )}
            </tbody>
            </table>
        </div>
        )}
      </div>

      {/* Add Modal */}
      {showAddModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
           <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md p-6 animate-fade-in-up border border-slate-100">
              <div className="flex justify-between items-center mb-6 border-b border-slate-100 pb-4">
                 <h2 className="text-xl font-bold text-slate-800">إضافة طالب جديد</h2>
                 <button onClick={() => setShowAddModal(false)} className="text-slate-400 hover:text-slate-600">✕</button>
              </div>
              
              <form onSubmit={handleAddStudent} className="space-y-4">
                 <div>
                   <label className={labelClasses}>الاسم الثلاثي</label>
                   <input required value={newName} onChange={e => setNewName(e.target.value)} className={inputClasses} placeholder="مثال: أحمد محمد علي" />
                 </div>
                 <div>
                   <label className={labelClasses}>رقم الهوية / السجل</label>
                   <input required value={newId} onChange={e => setNewId(e.target.value)} className={inputClasses} placeholder="1xxxxxxxxx" />
                 </div>
                 <div className="grid grid-cols-2 gap-4">
                    <div>
                       <label className={labelClasses}>الصف</label>
                       <select value={newGrade} onChange={e => setNewGrade(e.target.value)} className={inputClasses}>
                          {GRADES.map(g => <option key={g} value={g}>{g}</option>)}
                       </select>
                    </div>
                    <div>
                       <label className={labelClasses}>الفصل</label>
                       <select value={newClass} onChange={e => setNewClass(e.target.value)} className={inputClasses}>
                          {CLASSES.map(c => <option key={c} value={c}>{c}</option>)}
                       </select>
                    </div>
                 </div>
                 <div>
                   <label className={labelClasses}>رقم الجوال</label>
                   <input required value={newPhone} onChange={e => setNewPhone(e.target.value)} className={inputClasses} placeholder="05xxxxxxxx" />
                 </div>
                 <div className="flex gap-3 pt-4">
                   <button type="submit" className="flex-1 bg-blue-900 text-white py-2.5 rounded-lg hover:bg-blue-800 font-bold transition-colors shadow-lg shadow-blue-900/20">حفظ البيانات</button>
                   <button type="button" onClick={() => setShowAddModal(false)} className="flex-1 bg-slate-100 text-slate-700 py-2.5 rounded-lg hover:bg-slate-200 font-bold transition-colors">إلغاء</button>
                 </div>
              </form>
           </div>
        </div>
      )}
    </div>
  );
};

export default Students;