import { supabase } from '../supabaseClient';
import { Student, ExcuseRequest, RequestStatus, StaffUser, AttendanceRecord, AttendanceStatus } from "../types";

// --- Caching System ---
const CACHE: Record<string, { data: any, timestamp: number }> = {};
const CACHE_TTL = 15 * 60 * 1000; // 15 Minutes

export const getFromCache = <T>(key: string): T | null => {
  const cached = CACHE[key];
  if (cached && Date.now() - cached.timestamp < CACHE_TTL) {
    return cached.data as T;
  }
  return null;
};

const setCache = (key: string, data: any) => {
  CACHE[key] = { data, timestamp: Date.now() };
};

export const invalidateCache = (key: string) => {
  delete CACHE[key];
};

// --- MAPPING HELPERS (App uses CamelCase, DB uses snake_case) ---

const mapStudentFromDB = (s: any): Student => ({
  id: s.id,
  name: s.name,
  studentId: s.student_id,
  grade: s.grade,
  className: s.class_name,
  phone: s.phone || ''
});

const mapStudentToDB = (s: Student) => ({
  // id is usually auto-generated by DB, but if updating we might send it
  name: s.name,
  student_id: s.studentId,
  grade: s.grade,
  class_name: s.className,
  phone: s.phone
});

const mapRequestFromDB = (r: any): ExcuseRequest => ({
  id: r.id,
  studentId: r.student_id,
  studentName: r.student_name,
  grade: r.grade,
  className: r.class_name,
  date: r.date,
  reason: r.reason,
  details: r.details,
  attachmentName: r.attachment_name,
  attachmentUrl: r.attachment_url, // Added support for URL
  status: r.status as RequestStatus,
  submissionDate: r.submission_date
});

const mapRequestToDB = (r: ExcuseRequest) => ({
  student_id: r.studentId,
  student_name: r.studentName,
  grade: r.grade,
  class_name: r.className,
  date: r.date,
  reason: r.reason,
  details: r.details,
  attachment_name: r.attachmentName,
  attachment_url: r.attachmentUrl, // Added support for URL
  status: r.status,
  submission_date: r.submissionDate
});

const mapStaffFromDB = (u: any): StaffUser => ({
  id: u.id,
  name: u.name,
  passcode: u.passcode,
  assignments: u.assignments || [] // JSONB
});

const mapStaffToDB = (u: StaffUser) => ({
  name: u.name,
  passcode: u.passcode,
  assignments: u.assignments
});

const mapAttendanceFromDB = (a: any): AttendanceRecord => ({
  id: a.id,
  date: a.date,
  grade: a.grade,
  className: a.class_name,
  staffId: a.staff_id,
  records: a.records || [] // JSONB
});

const mapAttendanceToDB = (a: AttendanceRecord) => ({
  date: a.date,
  grade: a.grade,
  class_name: a.className,
  staff_id: a.staffId,
  records: a.records
});

// --- DIAGNOSTIC TOOL ---
export const testSupabaseConnection = async (): Promise<{ success: boolean; message: string }> => {
  try {
    const { data, error } = await supabase.from('students').select('count', { count: 'exact', head: true });
    
    if (error) throw error;
    
    return { success: true, message: `تم الاتصال بقاعدة بيانات Supabase بنجاح! (Status: Online)` };
  } catch (error: any) {
    console.error("Supabase Connection Test Error:", error);
    return { success: false, message: `فشل الاتصال: ${error.message || 'تأكد من مفاتيح الربط'}` };
  }
};

// --- STORAGE ---
// Function to upload file to Supabase Storage
export const uploadFile = async (file: File): Promise<string | null> => {
  try {
    const fileExt = file.name.split('.').pop();
    const fileName = `${Math.random().toString(36).substring(2)}_${Date.now()}.${fileExt}`;
    const filePath = `${fileName}`;

    const { error: uploadError } = await supabase.storage
      .from('attachments')
      .upload(filePath, file);

    if (uploadError) throw uploadError;

    const { data } = supabase.storage.from('attachments').getPublicUrl(filePath);
    return data.publicUrl;
  } catch (error) {
    console.error('Upload error:', error);
    return null;
  }
};

// --- STUDENTS ---

export const getStudentsSync = (): Student[] | null => getFromCache<Student[]>('students');

export const getStudents = async (forceRefresh = false): Promise<Student[]> => {
  if (!forceRefresh) {
    const cached = getFromCache<Student[]>('students');
    if (cached) return cached;
  }

  const { data, error } = await supabase
    .from('students')
    .select('*')
    .order('name');

  if (error) throw new Error(error.message);

  const students = data.map(mapStudentFromDB);
  setCache('students', students);
  return students;
};

export const getStudentByCivilId = async (civilId: string): Promise<Student | null> => {
  const { data, error } = await supabase
    .from('students')
    .select('*')
    .eq('student_id', civilId)
    .single();

  if (error || !data) return null;
  return mapStudentFromDB(data);
};

export const getAvailableClassesForGrade = async (grade: string): Promise<string[]> => {
  // Optimized: Use RPC or distinct query if possible, but for now cache filtering is fast enough for small datasets
  const students = await getStudents();
  const classes = new Set<string>();
  students.forEach(s => {
    if (s.grade === grade && s.className) classes.add(s.className);
  });
  return Array.from(classes).sort();
};

export const addStudent = async (student: Student): Promise<Student> => {
  const { data, error } = await supabase
    .from('students')
    .insert(mapStudentToDB(student))
    .select()
    .single();

  if (error) throw new Error(error.message);

  const newStudent = mapStudentFromDB(data);
  
  // Update Cache
  const cached = getFromCache<Student[]>('students');
  if (cached) setCache('students', [...cached, newStudent]);
  else invalidateCache('students');

  return newStudent;
};

export const deleteStudent = async (id: string) => {
  const { error } = await supabase.from('students').delete().eq('id', id);
  if (error) throw new Error(error.message);
  invalidateCache('students');
};

// Optimized Bulk Sync for Supabase
export const syncStudentsBatch = async (
  toAdd: Student[], 
  toUpdate: Student[], 
  toDeleteIds: string[]
) => {
  // 1. Handle Deletes
  if (toDeleteIds.length > 0) {
    const { error } = await supabase.from('students').delete().in('id', toDeleteIds);
    if (error) throw error;
  }

  // 2. Handle Adds & Updates using UPSERT
  // We assume 'student_id' is a unique key in the DB constraints
  const upsertData = [...toAdd, ...toUpdate].map(mapStudentToDB);
  
  if (upsertData.length > 0) {
    // Process in chunks of 500 to be safe, though Supabase can handle more
    const CHUNK_SIZE = 500;
    for (let i = 0; i < upsertData.length; i += CHUNK_SIZE) {
      const chunk = upsertData.slice(i, i + CHUNK_SIZE);
      
      const { error } = await supabase
        .from('students')
        .upsert(chunk, { onConflict: 'student_id' }); // Ensure student_id is UNIQUE in DB
      
      if (error) throw error;
    }
  }

  invalidateCache('students');
};

export const clearStudents = async () => {
  const { error } = await supabase.from('students').delete().neq('id', '00000000-0000-0000-0000-000000000000'); // Delete all
  if (error) throw error;
  invalidateCache('students');
};

// --- REQUESTS ---

export const getRequests = async (forceRefresh = false): Promise<ExcuseRequest[]> => {
  if (!forceRefresh) {
    const cached = getFromCache<ExcuseRequest[]>('requests');
    if (cached) return cached;
  }

  const { data, error } = await supabase
    .from('requests')
    .select('*')
    .order('submission_date', { ascending: false });

  if (error) throw new Error(error.message);

  const requests = data.map(mapRequestFromDB);
  setCache('requests', requests);
  return requests;
};

export const getRequestsByStudentId = async (studentId: string): Promise<ExcuseRequest[]> => {
  const { data, error } = await supabase
    .from('requests')
    .select('*')
    .eq('student_id', studentId)
    .order('submission_date', { ascending: false });

  if (error) return [];
  return data.map(mapRequestFromDB);
};

export const addRequest = async (req: ExcuseRequest) => {
  const { error } = await supabase.from('requests').insert(mapRequestToDB(req));
  if (error) throw error;
  invalidateCache('requests');
};

export const updateRequestStatus = async (id: string, status: RequestStatus) => {
  // If Approved or Rejected, we might want to clean up the file to save storage
  // But for now, we will keep the URL in DB but maybe delete file from bucket if needed.
  // Let's implement the cleanup logic requested: Delete file upon decision.
  
  if (status === RequestStatus.APPROVED || status === RequestStatus.REJECTED) {
     // 1. Get the attachment URL first
     const { data: reqData } = await supabase.from('requests').select('attachment_url').eq('id', id).single();
     
     if (reqData?.attachment_url) {
        // Extract file path from URL. URL format: .../attachments/filename
        const urlParts = reqData.attachment_url.split('/');
        const fileName = urlParts[urlParts.length - 1];
        
        // Delete from Storage
        await supabase.storage.from('attachments').remove([fileName]);
        
        // Update DB to remove URL but keep Name (and mark as deleted)
        await supabase.from('requests').update({ 
            status, 
            attachment_url: null 
        }).eq('id', id);
        
        invalidateCache('requests');
        return;
     }
  }

  const { error } = await supabase
    .from('requests')
    .update({ status })
    .eq('id', id);
  
  if (error) throw error;
  invalidateCache('requests');
};

export const clearRequests = async () => {
  const { error } = await supabase.from('requests').delete().neq('id', '00000000-0000-0000-0000-000000000000');
  if (error) throw error;
  invalidateCache('requests');
};

// --- STAFF ---

export const getStaffUsersSync = (): StaffUser[] | null => getFromCache<StaffUser[]>('staff');

export const getStaffUsers = async (forceRefresh = false): Promise<StaffUser[]> => {
  if (!forceRefresh) {
    const cached = getFromCache<StaffUser[]>('staff');
    if (cached) return cached;
  }

  const { data, error } = await supabase.from('staff').select('*');
  if (error) throw error;

  const staff = data.map(mapStaffFromDB);
  setCache('staff', staff);
  return staff;
};

export const addStaffUser = async (user: StaffUser) => {
  const { error } = await supabase.from('staff').insert(mapStaffToDB(user));
  if (error) throw error;
  invalidateCache('staff');
};

export const deleteStaffUser = async (id: string) => {
  const { error } = await supabase.from('staff').delete().eq('id', id);
  if (error) throw error;
  invalidateCache('staff');
};

export const authenticateStaff = async (passcode: string): Promise<StaffUser | null> => {
  const { data, error } = await supabase
    .from('staff')
    .select('*')
    .eq('passcode', passcode)
    .single();

  if (error || !data) return null;
  return mapStaffFromDB(data);
};

// --- ATTENDANCE ---

export const getAttendanceRecords = async (forceRefresh = false): Promise<AttendanceRecord[]> => {
  if (!forceRefresh) {
    const cached = getFromCache<AttendanceRecord[]>('attendance');
    if (cached) return cached;
  }

  const { data, error } = await supabase.from('attendance').select('*');
  if (error) throw error;

  const records = data.map(mapAttendanceFromDB);
  setCache('attendance', records);
  return records;
};

export const getAttendanceRecordForClass = async (date: string, grade: string, className: string): Promise<AttendanceRecord | null> => {
  const { data, error } = await supabase
    .from('attendance')
    .select('*')
    .eq('date', date)
    .eq('grade', grade)
    .eq('class_name', className)
    .single();

  if (error || !data) return null;
  return mapAttendanceFromDB(data);
};

export const saveAttendanceRecord = async (record: AttendanceRecord) => {
  // Logic: Check if record exists for Date + Grade + Class
  const { data: existing } = await supabase
    .from('attendance')
    .select('id')
    .eq('date', record.date)
    .eq('grade', record.grade)
    .eq('class_name', record.className)
    .single();

  if (existing) {
    // Update
    await supabase
      .from('attendance')
      .update({ 
        records: record.records,
        staff_id: record.staffId
      })
      .eq('id', existing.id);
  } else {
    // Insert
    await supabase.from('attendance').insert(mapAttendanceToDB(record));
  }
  
  invalidateCache('attendance');
};

export const clearAttendance = async () => {
  const { error } = await supabase.from('attendance').delete().neq('id', '00000000-0000-0000-0000-000000000000');
  if (error) throw error;
  invalidateCache('attendance');
};

// Helpers

export const getStudentAttendanceHistory = async (studentId: string, grade: string, className: string): Promise<{ date: string, status: AttendanceStatus }[]> => {
  // Optimized query
  const { data, error } = await supabase
    .from('attendance')
    .select('date, records')
    .eq('grade', grade)
    .eq('class_name', className);

  if (error || !data) return [];

  const history: { date: string, status: AttendanceStatus }[] = [];
  
  data.forEach((row: any) => {
    // row.records is JSONB array
    const recordList = row.records as any[];
    const studentEntry = recordList.find((r: any) => r.studentId === studentId);
    if (studentEntry) {
      history.push({
        date: row.date,
        status: studentEntry.status as AttendanceStatus
      });
    }
  });

  return history.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
};

export const getDailyAttendanceReport = async (date: string) => {
  const { data, error } = await supabase
    .from('attendance')
    .select('*')
    .eq('date', date);

  if (error) return { totalPresent: 0, totalAbsent: 0, totalLate: 0, details: [] };

  const dayRecords = data.map(mapAttendanceFromDB);
  
  let totalPresent = 0;
  let totalAbsent = 0;
  let totalLate = 0;
  const details: any[] = [];

  dayRecords.forEach(record => {
    record.records.forEach(student => {
      if (student.status === AttendanceStatus.PRESENT) totalPresent++;
      if (student.status === AttendanceStatus.ABSENT) totalAbsent++;
      if (student.status === AttendanceStatus.LATE) totalLate++;
      
      if (student.status !== AttendanceStatus.PRESENT) {
        details.push({
          studentName: student.studentName,
          grade: record.grade,
          className: record.className,
          status: student.status
        });
      }
    });
  });

  return { totalPresent, totalAbsent, totalLate, details };
};